org: orgDemo
app: appDemo
stage: dev
component: thinkphp
name: thinkphpDemo

inputs:
  src:
    src: ./
    exclude:
      - .env
  # region: ap-guangzhou
  # runtime: Php7
  # apigatewayConf:
  #   protocols:
  #     - http
  #     - https
  #   environment: release
